# name: deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: npm install && npm run build
#       - name: Publish
#         run: npm run publish
#         env:
#           CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
#       - uses: atymic/sitemap-ping-action@main
#         with:
#           sitemap-url: ${{ secrets.SITEMAP_URL }}
